apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pylerry.fullname" . }}
  labels:
    {{- include "pylerry.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pylerry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pylerry.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pylerry.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /dir/
              port: http
          readinessProbe:
            httpGet:
              path: /dir/
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: LISTEN_HOST
              value: "0.0.0.0"
            - name: LISTEN_PORT
              value: "80"
          volumeMounts:
            - name: photos
              mountPath: /data/photos
              readOnly: true
            - name: thumbnails
              mountPath: /data/thumbnails
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: photos
          {{- toYaml .Values.storage.photos.volume | nindent 10 }}
        {{- range .Values.storage.photos.mounts }}
        {{- end }}
        - name: thumbnails 
          {{ if .Values.storage.existing.thumbnails }}
          {{- toYaml .Values.storage.existing.thumbnails | nindent 10 }}
          {{ else }}
          persistentVolumeClaim:
            claimName: {{ include "pylerry.fullname" . }}-thumbnails
          {{ end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}