{{ if not .Values.storage.existing.thumbnails }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "pylerry.fullname" . }}-thumbnails
  annotations:
    # nfs.io/storage-path: "test-path" # not required, depending on whether this annotation was shown in the storage class description
  labels:
    {{- include "pylerry.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.thumbnails.size | default "100Gi" }}
{{ end }}